name: string_method
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - mdanalysis
  - numpy
  - pip
  - python=3.8.5
  - matplotlib
  - seaborn
  - mpi4py
  - scikit-build
  - setuptools
  - pip:
       - gmxapi==0.1.0.1
