name: string_method 
channels:
  - conda-forge
  - defaults
dependencies:
  - mdanalysis
  - nglview=2.7.7
  - nodejs
  - ipywidgets=7.5.1
  - jupyterlab=2.2.6
  - numpy
  - pip
  - python=3.8.5
  - matplotlib
  - seaborn
  - mpi4py
  - pip:
      - gmxapi==0.2.0a1
        
# Use the commandline to install nglview-js-widgets in this way:
# jupyter labextension install nglview-js-widgets@2.7.7
# jupyter-labextension install @jupyter-widgets/jupyterlab-manager
